export const UPDATE_DATE = 'UPDATE_DATE';
export const UPDATE_TERM = 'UPDATE_TERM';
export const SELECT_ACCOUNT = 'SELECT_ACCOUNT';
export const DESELECT_ACCOUNT = 'DESELECT_ACCOUNT';
export const SELECT_GROUPING = 'SELECT_GROUPING';
export const DESELECT_GROUPING = 'DESELECT_GROUPING';
export const SELECT_BUDGET = 'SELECT_BUDGET';
export const DESELECT_BUDGET = 'DESELECT_BUDGET';
