const WRITE_ACCOUNT = "WRITE_ACCOUNT";
const WIPE_ACCOUNTS = "WIPE_ACCOUNTS";
const WRITE_ACCOUNTS = "WRITE_ACCOUNTS";
const WRITE_GROUPINGS = "WRITE_GROUPINGS";
const WRITE_GROUPING = "WRITE_GROUPING";
const WIPE_GROUPINGS = "WIPE_GROUPINGS";
const INIT_API = "INIT_API";
const CLOSE_API = "CLOSE_API";
const CREATE_SUCCESS_MESSAGE = "CREATE_SUCCESS_MESSAGE";
const CREATE_ERROR_MESSAGE = "CREATE_ERROR_MESSAGE";
const DISMISS_MESSAGE = "DISMISS_MESSAGE";
const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";
const REMOVE_GROUPING = "REMOVE_GROUPING";
const WIPE_TRANSACTIONS = "WIPE_TRANSACTIONS";
const WRITE_TRANSACTION = "WRITE_TRANSACTION";
const REMOVE_TRANSACTION = "REMOVE_TRANSACTION";
const WRITE_TRANSACTIONS = "WRITE_TRANSACTIONS";
const WRITE_BUDGET = "WRITE_BUDGET";
const WRITE_BUDGETS = "WRITE_BUDGETS";
const REMOVE_BUDGET = "REMOVE_BUDGET";
const WIPE_BUDGETS = "WIPE_BUDGETS";
const RESTORE_TO_INITIAL_STATE = 'RESTORE_TO_INITIAL_STATE';

export {
  REMOVE_GROUPING,
  REMOVE_ACCOUNT,
  WRITE_ACCOUNT,
  WIPE_ACCOUNTS,
  INIT_API,
  CLOSE_API,
  CREATE_SUCCESS_MESSAGE,
  CREATE_ERROR_MESSAGE,
  DISMISS_MESSAGE,
  WIPE_GROUPINGS,
  WRITE_GROUPING,
  WRITE_GROUPINGS,
  WRITE_ACCOUNTS,
  WRITE_TRANSACTION,
  WRITE_TRANSACTIONS,
  REMOVE_TRANSACTION,
  WIPE_TRANSACTIONS,
  WRITE_BUDGET,
  WRITE_BUDGETS,
  REMOVE_BUDGET,
  WIPE_BUDGETS,
  RESTORE_TO_INITIAL_STATE
};
